import { router } from 'expo-router';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Alert, View } from 'react-native';

import { useLinkPlanItemRecipe } from './hooks';

import { AppText, Button, Card, LoadingState, MacroSummary, Sheet } from '@/components/ui';
import {
  draftRecipeFromText,
  draftToInput,
  useCreateRecipe,
  useRecipe,
} from '@/features/recipes/hooks';
import { AiError } from '@/lib/ai/client';
import { useTheme } from '@/theme';
import type { MealPlanItem } from '@/types/domain';
import { formatQuantity } from '@/utils/units';

interface PlanMealSheetProps {
  item: MealPlanItem | null;
  onClose: () => void;
}

/**
 * Bottom sheet for a planned meal: description + macros, and the full recipe
 * (ingredients + steps). Plans generated by AI ship without recipes — the
 * first tap can generate one, which is saved to the user's recipe book and
 * linked to the plan item for next time.
 */
export function PlanMealSheet({ item, onClose }: PlanMealSheetProps) {
  const { t } = useTranslation();
  const theme = useTheme();

  const [linkedRecipeId, setLinkedRecipeId] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const recipeId = item?.recipe_id ?? linkedRecipeId ?? '';
  const { data: recipe, isLoading: loadingRecipe } = useRecipe(recipeId);
  const createRecipe = useCreateRecipe();
  const linkRecipe = useLinkPlanItemRecipe();

  const close = () => {
    setLinkedRecipeId(null);
    setGenerating(false);
    onClose();
  };

  const generateRecipe = async () => {
    if (!item) return;
    setGenerating(true);
    try {
      const prompt = item.description ? `${item.title}: ${item.description}` : item.title;
      const draft = await draftRecipeFromText(prompt, 'generate');
      createRecipe.mutate(draftToInput(draft), {
        onSuccess: (newId) => {
          setLinkedRecipeId(newId);
          linkRecipe.mutate({ itemId: item.id, recipeId: newId });
          setGenerating(false);
        },
        onError: () => {
          Alert.alert(t('errors.generic'), t('errors.genericBody'));
          setGenerating(false);
        },
      });
    } catch (error) {
      setGenerating(false);
      if (error instanceof AiError && error.code === 'premium_required') {
        close();
        router.push('/profile/premium');
      } else if (error instanceof AiError && error.code === 'quota_exceeded') {
        Alert.alert(t('premium.quotaTitle'), t('errors.quotaExceeded'));
      } else {
        Alert.alert(t('errors.generic'), t('ai.error'));
      }
    }
  };

  return (
    <Sheet
      visible={item != null}
      onClose={close}
      title={item ? t(`today.${item.meal_type === 'flexible' ? 'flexibleMeal' : item.meal_type}`) : ''}
    >
      {item ? (
        <>
          <AppText variant="title">{item.title}</AppText>
          {item.description ? (
            <AppText variant="body" color="secondary">
              {item.description}
            </AppText>
          ) : null}
          {item.nutrients ? (
            <Card muted>
              <MacroSummary nutrients={item.nutrients} />
            </Card>
          ) : null}

          {generating ? (
            <LoadingState label={t('planning.generatingRecipe')} />
          ) : recipeId && loadingRecipe ? (
            <LoadingState />
          ) : recipe ? (
            <>
              <AppText variant="headline">{t('recipes.fields.ingredients')}</AppText>
              <Card style={{ gap: theme.spacing.sm }}>
                {recipe.ingredients.map((ingredient, index) => (
                  <View
                    key={`${ingredient.name}-${index}`}
                    style={{ flexDirection: 'row', justifyContent: 'space-between', gap: theme.spacing.md }}
                  >
                    <AppText variant="body" style={{ flex: 1 }}>
                      {ingredient.name}
                    </AppText>
                    <AppText variant="body" color="secondary" style={{ fontVariant: ['tabular-nums'] }}>
                      {formatQuantity(ingredient.quantity, ingredient.unit)}
                    </AppText>
                  </View>
                ))}
              </Card>

              <AppText variant="headline">{t('recipes.fields.steps')}</AppText>
              <Card style={{ gap: theme.spacing.md }}>
                {recipe.steps.map((step, index) => (
                  <View key={index} style={{ flexDirection: 'row', gap: theme.spacing.md }}>
                    <AppText variant="headline" color="accent">
                      {index + 1}
                    </AppText>
                    <AppText variant="body" style={{ flex: 1 }}>
                      {step}
                    </AppText>
                  </View>
                ))}
              </Card>

              <Button
                label={t('planning.openRecipe')}
                variant="secondary"
                icon="recipes"
                onPress={() => {
                  close();
                  router.push({ pathname: '/recipes/[id]', params: { id: recipe.id } });
                }}
              />
            </>
          ) : (
            <>
              <AppText variant="footnote" color="tertiary">
                {t('planning.noRecipeYet')}
              </AppText>
              <Button
                label={t('planning.generateRecipe')}
                icon="sparkles"
                onPress={() => void generateRecipe()}
                loading={createRecipe.isPending}
              />
            </>
          )}
        </>
      ) : null}
    </Sheet>
  );
}
